import React, { useState, useEffect } from 'react';
import { reportApi, alertApi } from '../api';
import { RiskBadge, FraudTypeBadge } from '../components/Badges';
import { formatDate, formatCurrency } from '../utils/format';
import { FileText, Download, BarChart2, TrendingUp } from 'lucide-react';
import {
    BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip,
    ResponsiveContainer, PieChart, Pie, Cell, LineChart, Line
} from 'recharts';

const PIE_COLORS = ['#ef4444', '#f97316', '#a855f7', '#eab308', '#3b82f6', '#ec4899', '#06b6d4', '#f43f5e'];

export default function ReportsPage() {
    const [summary, setSummary] = useState<any>(null);
    const [reports, setReports] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [selectedReport, setSelectedReport] = useState<any>(null);

    useEffect(() => {
        const load = async () => {
            try {
                const [sumRes, repsRes] = await Promise.all([reportApi.summary(), reportApi.list({ limit: 10 })]);
                setSummary(sumRes.data);
                setReports(repsRes.data.reports || []);
            } catch (e) { console.error(e); }
            finally { setLoading(false); }
        };
        load();
    }, []);

    const downloadReport = (report: any) => {
        if (!report.aiReport) return;
        import('jspdf').then(({ jsPDF }) => {
            const doc = new jsPDF();
            const margin = 15;
            let y = 20;
            const pageHeight = doc.internal.pageSize.getHeight();

            doc.setFontSize(16);
            doc.setTextColor(13, 34, 68);
            doc.text(`BFI AI Investigation Report`, margin, y);
            y += 8;

            doc.setFontSize(10);
            doc.setTextColor(100, 116, 139);
            const reportDate = new Date(report.aiReportGeneratedAt).toLocaleDateString();
            doc.text(`Alert ID: ${report.alertId} | Generated on ${reportDate}`, margin, y);
            y += 15;

            doc.setFontSize(10);
            doc.setTextColor(30, 41, 59);

            const cleanText = report.aiReport.replace(/\*\*(.*?)\*\*/g, '$1').replace(/#(.*?)\n/g, '$1\n');
            const lines = doc.splitTextToSize(cleanText, 180);

            for (let i = 0; i < lines.length; i++) {
                if (y > pageHeight - margin) {
                    doc.addPage();
                    y = margin;
                }
                doc.text(lines[i], margin, y);
                y += 5.5;
            }

            doc.save(`BFI-${report.alertId}.pdf`);
        });
    };

    const fraudByType = summary?.fraudByType?.map((d: any, i: number) => ({
        name: d._id || 'Unknown',
        value: d.count,
        amount: d.totalAmount,
        color: PIE_COLORS[i % PIE_COLORS.length],
    })) || [];

    const monthlyTrends = summary?.monthlyTrends?.map((d: any) => ({
        month: d._id,
        total: d.total,
        fraud: d.fraud,
        amount: Math.round((d.amount || 0) / 100000),
    })) || [];

    return (
        <div className="animate-fade-in">
            <div className="mb-6">
                <h1 className="page-title">Investigation Reports</h1>
                <p className="page-subtitle">AI-generated fraud analysis reports and compliance documentation</p>
            </div>

            <div className="info-panel">
                <p>
                    <strong className="text-teal-400">Investigation Reports</strong> are generated by the BFI GenAI engine
                    for each fraud alert. Reports include fraud pattern analysis, transaction timeline, risk assessment,
                    and recommended investigative actions. All reports can be exported for regulatory compliance.
                </p>
            </div>

            {/* Summary Charts */}
            {!loading && summary && (
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 mb-6">
                    {/* Fraud by Type Pie */}
                    <div className="glass-card p-5">
                        <h3 className="text-sm font-semibold text-white mb-4 flex items-center gap-2">
                            <BarChart2 size={14} className="text-teal-400" /> Fraud by Type
                        </h3>
                        <ResponsiveContainer width="100%" height={180}>
                            <PieChart>
                                <Pie data={fraudByType} cx="50%" cy="50%" innerRadius={45} outerRadius={75} dataKey="value" paddingAngle={2}>
                                    {fraudByType.map((e: any, i: number) => <Cell key={i} fill={e.color} />)}
                                </Pie>
                                <Tooltip contentStyle={{ background: '#0d2244', border: '1px solid rgba(45,212,191,0.2)', borderRadius: 8, color: '#e2e8f0', fontSize: 12 }} />
                            </PieChart>
                        </ResponsiveContainer>
                        <div className="space-y-1.5">
                            {fraudByType.slice(0, 4).map((e: any) => (
                                <div key={e.name} className="flex items-center justify-between text-xs">
                                    <span className="flex items-center gap-1.5 text-slate-400">
                                        <span className="w-2 h-2 rounded-full" style={{ background: e.color }} />
                                        {e.name}
                                    </span>
                                    <span className="text-white font-semibold">{e.value}</span>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Monthly Trends */}
                    <div className="lg:col-span-2 glass-card p-5">
                        <h3 className="text-sm font-semibold text-white mb-4 flex items-center gap-2">
                            <TrendingUp size={14} className="text-teal-400" /> Monthly Fraud Trends
                        </h3>
                        <ResponsiveContainer width="100%" height={220}>
                            <BarChart data={monthlyTrends}>
                                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                                <XAxis dataKey="month" tick={{ fill: '#64748b', fontSize: 10 }} />
                                <YAxis tick={{ fill: '#64748b', fontSize: 10 }} />
                                <Tooltip contentStyle={{ background: '#0d2244', border: '1px solid rgba(45,212,191,0.2)', borderRadius: 8, color: '#e2e8f0', fontSize: 11 }} />
                                <Bar dataKey="total" fill="rgba(20,184,166,0.4)" name="Total Txns" />
                                <Bar dataKey="fraud" fill="rgba(239,68,68,0.6)" name="Fraud Txns" />
                            </BarChart>
                        </ResponsiveContainer>
                    </div>
                </div>
            )}

            {/* Top Risky Accounts */}
            {summary?.topAccounts?.length > 0 && (
                <div className="glass-card p-5 mb-6">
                    <h3 className="text-sm font-semibold text-white mb-4">🔴 Top Risk Accounts</h3>
                    <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">
                        {summary.topAccounts.map((acc: any) => (
                            <div key={acc.accountId} className="p-3 bg-navy-800/50 rounded-lg border border-red-500/20">
                                <div className="text-xs font-mono text-teal-400 font-semibold truncate">{acc.accountId}</div>
                                <div className="mt-1"><RiskBadge score={acc.riskScore} size="sm" /></div>
                                <div className="text-[10px] text-slate-500 mt-1 capitalize">{acc.riskLevel}</div>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* AI Reports List */}
            <div className="glass-card p-5">
                <div className="flex items-center justify-between mb-4">
                    <h3 className="text-sm font-semibold text-white flex items-center gap-2">
                        <FileText size={14} className="text-teal-400" />
                        AI Investigation Reports ({reports.length})
                    </h3>
                </div>

                {reports.length === 0 ? (
                    <div className="text-center py-10 text-slate-500">
                        <FileText size={36} className="mx-auto mb-3 opacity-30" />
                        <p>No AI reports generated yet. Open an alert and click "Generate AI Report".</p>
                    </div>
                ) : (
                    <div className="space-y-3">
                        {reports.map(report => (
                            <div
                                key={report.alertId}
                                className="p-4 bg-navy-800/50 rounded-lg border border-white/5 hover:border-teal-500/30 transition-colors"
                            >
                                <div className="flex items-center justify-between flex-wrap gap-3">
                                    <div className="flex items-center gap-3">
                                        <FileText size={16} className="text-teal-400" />
                                        <div>
                                            <div className="text-sm font-mono text-teal-400 font-semibold">{report.alertId}</div>
                                            <div className="text-xs text-slate-500 mt-0.5">
                                                Account: {report.accountId} · Generated: {formatDate(report.aiReportGeneratedAt)}
                                            </div>
                                        </div>
                                    </div>
                                    <div className="flex items-center gap-3">
                                        <FraudTypeBadge type={report.fraudType} />
                                        <RiskBadge score={report.riskScore} size="sm" />
                                        <button
                                            onClick={() => setSelectedReport(report === selectedReport ? null : report)}
                                            className="text-xs text-teal-400 hover:underline"
                                        >
                                            {report === selectedReport ? 'Hide' : 'View'}
                                        </button>
                                        <button
                                            onClick={() => downloadReport(report)}
                                            className="flex items-center gap-1 text-xs text-slate-400 hover:text-teal-400 transition-colors"
                                        >
                                            <Download size={12} /> Export
                                        </button>
                                    </div>
                                </div>

                                {selectedReport === report && (
                                    <div className="mt-4 bg-navy-950/70 rounded-lg p-4 border border-white/5 max-h-64 overflow-y-auto">
                                        <pre className="text-xs text-slate-300 whitespace-pre-wrap font-mono leading-relaxed">
                                            {report.aiReport}
                                        </pre>
                                    </div>
                                )}
                            </div>
                        ))}
                    </div>
                )}
            </div>
        </div>
    );
}
